# Generated by Django 4.2.11 on 2024-03-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(),
        ),
    ]
