# Generated by Django 4.2.11 on 2024-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='google_plus_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(max_length=100),
        ),
    ]
